# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build README

on:
  push:
    branches:
      - main
      - develop
      - update-README
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: "32 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python 3.14.3
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.3

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv pip install --system .

      - name: Update README
        run: |
          python build_readme.py
          cat README.md

      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "wayne.a.lambert@gmail.com"
          git config --global user.name $GITHUB_ACTOR
          git diff --quiet || (git add README.md && git commit -m "Update README")
          git push
