name: Build README

on:
  push:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
  schedule:
    - cron: '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install Python dependencies
      run: |
        pipenv install --system --ignore-pipfile
    - name: Update README
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "wayne.a.lambert@gmail.com"
        git config --global user.name $GITHUB_ACTOR
        git diff --quiet || (git add README.md && git commit -m "Update README")
        git push
